services:
  - type: web
    name: memory-game-api
    runtime: python
    repo: https://github.com/amirros66/Memory-Game-Back-End.git
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pipenv install
    startCommand: ./bin/start.sh
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: memory-game-db
          property: connectionString

databases:
  - name: memory-game-db
    region: frankfurt
    plan: free
    databaseName: memory_game
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
