"""Add Score table

Revision ID: 4bbd92163ed1
Revises: a16e0d7744b8
Create Date: 2024-01-31 13:37:59.671992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbd92163ed1'
down_revision: Union[str, None] = 'a16e0d7744b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correct_guesses', sa.Integer(), nullable=True),
    sa.Column('incorrect_guesses', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_sequence_id', sa.Integer(), nullable=True),
    sa.Column('input_sequence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['display_sequence_id'], ['display_sequences.id'], ),
    sa.ForeignKeyConstraint(['input_sequence_id'], ['input_sequences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
