"""Add game_id to input sequences table

Revision ID: 5430fd5e0e92
Revises: 6c0e2b411b02
Create Date: 2024-03-11 13:13:33.832522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5430fd5e0e92'
down_revision: Union[str, None] = '6c0e2b411b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_sequences', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'input_sequences', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'input_sequences', type_='foreignkey')
    op.drop_column('input_sequences', 'game_id')
    # ### end Alembic commands ###
