"""Get rid of game_id from input sequences table

Revision ID: 6c0e2b411b02
Revises: d805071370b8
Create Date: 2024-02-01 16:45:58.711673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0e2b411b02'
down_revision: Union[str, None] = 'd805071370b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('input_sequences_game_id_fkey', 'input_sequences', type_='foreignkey')
    op.drop_column('input_sequences', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_sequences', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('input_sequences_game_id_fkey', 'input_sequences', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
