"""Add single column to game table

Revision ID: 76076b6f1ed4
Revises: 5430fd5e0e92
Create Date: 2024-04-02 22:54:14.803516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76076b6f1ed4'
down_revision: Union[str, None] = '5430fd5e0e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('single', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'single')
    # ### end Alembic commands ###
