"""Remove correct + incorrect guesses columns from user table

Revision ID: a16e0d7744b8
Revises: 9eb0d8f7b274
Create Date: 2024-01-31 11:42:52.651325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16e0d7744b8'
down_revision: Union[str, None] = '9eb0d8f7b274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'incorrect_guesses')
    op.drop_column('users', 'correct_guesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('correct_guesses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('incorrect_guesses', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
