"""Update Game table

Revision ID: a1dbeffcaef7
Revises: d7ff1afcf6e9
Create Date: 2024-04-03 00:04:35.984160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dbeffcaef7'
down_revision: Union[str, None] = 'd7ff1afcf6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
