"""Update InputSequence table

Revision ID: d7ff1afcf6e9
Revises: 76076b6f1ed4
Create Date: 2024-04-03 00:00:34.222463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ff1afcf6e9'
down_revision: Union[str, None] = '76076b6f1ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('input_sequences_game_id_fkey', 'input_sequences', type_='foreignkey')
    op.drop_column('input_sequences', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_sequences', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('input_sequences_game_id_fkey', 'input_sequences', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
