"""Update tables

Revision ID: d805071370b8
Revises: 4bbd92163ed1
Create Date: 2024-02-01 12:28:13.973050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd805071370b8'
down_revision: Union[str, None] = '4bbd92163ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('display_sequences', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'display_sequences', 'games', ['game_id'], ['id'])
    op.add_column('input_sequences', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'input_sequences', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'input_sequences', type_='foreignkey')
    op.drop_column('input_sequences', 'game_id')
    op.drop_constraint(None, 'display_sequences', type_='foreignkey')
    op.drop_column('display_sequences', 'game_id')
    # ### end Alembic commands ###
